### PR TITLE
create age filter to convert birthday to age

### PR DESCRIPTION
**Pull request by PhucCes**
https://app.asana.com/0/348819471518170/517745057081627/f
I created a filter to return human's age from date input.

### CODE REVIEW

**Comment by PhucCes** [comment]
@alexgurrola I created a filter to return human's age from date input. But I can't use it on Symfony side. Can you help to take a look at this?
I used it on [this line](https://github.com/gutensite/Sitetheory/pull/175/files#diff-644ac3cb731b6135784cf18de85fea84R41).

**Comment by alexgurrola** [comment]
I put a more permanent fix into the Stratus core today to autoload Filters.  Enjoy!

**Comment by alexgurrola** [comment]
I put a more permanent fix into the Stratus core today with https://github.com/Sitetheory/stratus/commit/292b1c0c1c9a7ac4d6df8aff8b28ebc123449aa4 to autoload all Filters. Enjoy!

**Comment by PhucCes** [comment]
Thank you, @alexgurrola

**Comment by PhucCes** [comment]
@alexgurrola I fix the conflict, can you help to review it again? 
Thank you :D

**Pull request merged**
