### PR TITLE
Basic Model AutoSave

### PR DESCRIPTION
**Pull request by alexgurrola**
Adds:

- Basic AutoSave Logic

### CODE REVIEW

**Comment by alexgurrola** [comment]
@apocist If you change `model.autosave` to `false`, it will halt the auto-saving process, even if it's currently in the middle of an AutoSave timer.

**Comment by apocist** [comment]
@alexgurrola 
I meant that It'll just tell the saving autoprocess not to do anything while the timeout clicks.  But if the timeout process what already counting down, but autosave is disabled, and then enabled again, it doesn't reset. So it could essentially save after a split second of a change. (but I guess that's not that big a deal).

Basically right now autosave attempts to happen every 10 seconds. And enabling/disabling doesn't interrupt that process or reset the cooldown

**Comment by apocist** [comment]
actually wait... if this is on every single model by default... doesn't that mean it could be really intense to load collections?

Each model in a collection will have a timeout constantly kicking off.

**Comment by alexgurrola** [comment]
@apocist Good point.  I can change the logic a bit so that it actually stops the processes in place, but that also comes with the issue that it would need another change after being enabled to kick the routine off.  Does that work for your focus even workflow?

**Comment by alexgurrola** [comment]
@apocist The AutoSave only kicks off if a valid changeSet is detected, so it runs passively.  The only thing running actively is the watcher on the model which has always been there.

**Comment by apocist** [comment]
@alexgurrola I didn't notice that the autosave wouldn't even set if the model wasn't already completed. So that means the autosave will never load until manually enabled? (as the model probably won't be `complete` when it first loads)

But once it does enable `saveIdle()`, theres no way to stop it.

**Pull request merged**
